### ISSUE TITLE
Perform common actions with proxy wasm go

### ISSUE THREAD

**Issue by menakaj** [mathetake/proxy-wasm-go#2]
Hi,

While experimenting with the SDK, I was trying to do actions like JSON decoding the headers etc.

The code is compiling but throws an error when starting up envoy. 

`proxy_1  | Failed to load WASM module due to a missing import: env.syscall/js.valueGet
`
I was also trying to do io stuff like reading a file etc. But got the same error.

What could be the reason for this? Would there be any workaround which can be done in the sdk level to fix this?

**Comment by mathetake** [comment]
looks like you call or import functions which use systemcall, which is not possible with proxy-wasm's host environment.

WASM does not specify such an _host environment_ and that's because WASI exists.

Proxy-wasm's host environment is kind of a bare metal with some host functions in [proxy-wasm](https://github.com/proxy-wasm/spec) specification.


This link here would be helpful to understand the situation: https://stackoverflow.com/questions/60969344/what-is-the-relationship-between-wasi-and-proxy-wasm/60995978#60995978
